---
title: "README"
date: "`r Sys.Date()`"
author:
  - name: Arun Seetharam
  - name: Jeffrey Haltom
    affiliation: Wurtele Lab
    affiliation_url: 
output:
  rmdformats::html_clean:
    self_contained: true
    thumbnails: false
    lightbox: true
    gallery: true
    highlight: tango
---

```{r setup, include=FALSE}
options(max.print = "75")
knitr::opts_chunk$set(
  echo = TRUE,
  collapse = TRUE,
  comment = "#>",
  fig.path = "assets/",
  fig.width = 8,
  prompt = FALSE,
  tidy = FALSE,
  message = FALSE,
  warning = TRUE
)
knitr::opts_knit$set(width = 75)
```

## Header



## Publication


_coming soon_

## Contacts



## Documentation


## Data availability

The data used in this study are publicly available:

| study_accession                            | Title                                                                                                                                                                     | Runs | Study Type   | Type      |
|--------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------|--------------|-----------|
| [ERP122190](ERP122190_multiqc_report.html) | Multi-level proteomics reveals host-perturbation strategies of SARS-CoV-2   and SARS-CoV.                                                                                 | 73   | Bulk RNA-Seq | Cell line |
| [ERP124749](ERP124749_multiqc_report.html) | RNA-seq of SARS-CoV-2-infected human primary hepatocyte-derived spheroids   upon interferon a2 and baricitinib treatment                                                  | 12   | Bulk RNA-Seq | Cell line |
| [SRP256166](SRP256166_multiqc_report.html) | Modeling SARS-Cov-2 Infection in Human Airway Epithelium Organoids   Transcriptome                                                                                        | 8    | Bulk RNA-Seq | Cell line |
| [SRP258687](SRP258687_multiqc_report.html) | Bulk RNA sequencing of SARS-CoV and SARS-CoV-2 infected human intestinal   organoids                                                                                      | 22   | Bulk RNA-Seq | Cell line |
| [SRP265388](SRP265388_multiqc_report.html) | Experimental and natural evidence of SARS-CoV-2 infection-induced   activation of type I interferon responses                                                             | 36   | Bulk RNA-Seq | Cell line |
| [SRP266130](SRP266130_multiqc_report.html) | Cardiomyocytes Infected by SARS-CoV-2 Recruit Cardiotoxic Macrophages   [bulk RNA-seq dataset)                                                                            | 18   | Bulk RNA-Seq | Cell line |
| [SRP269721](SRP269721_multiqc_report.html) | SARS-CoV-2 infection and replication in human fetal and pediatric gastric   organoids                                                                                     | 18   | Bulk RNA-Seq | Cell line |
| [SRP271173](SRP271173_multiqc_report.html) | Targeting heparan sulfate proteoglycan-assisted endocytosis as a COVID-19   therapeutic option                                                                            | 15   | Bulk RNA-Seq | Cell line |
| [SRP272808](SRP272808_multiqc_report.html) | A human disease model of SARS-CoV-2-induced lung injury and immune   responses with a microengineered organ chip                                                          | 12   | Bulk RNA-Seq | Cell line |
| [SRP273808](SRP273808_multiqc_report.html) | Identification of Drugs Blocking SARS-CoV-2 Infection using hPSC-derived   Lung and Colonic Organoids                                                                     | 18   | Bulk RNA-Seq | Cell line |
| [SRP273970](SRP273970_multiqc_report.html) | SARS-CoV-2 infection is effectively treated and prevented by EIDD-2801                                                                                                    | 26   | Bulk RNA-Seq | Cell line |
| [SRP278486](SRP278486_multiqc_report.html) | RNA-Sequencing of intestinal eithelial and endothelial cells upon   SARS-CoV-2 infection on a intestine chip                                                              | 12   | Bulk RNA-Seq | Cell line |
| [SRP278618](SRP278618_multiqc_report.html) | SARS-CoV2 infection of iPSC-derived cardiac cells predicts novel   cytopathic features in COVID-19 patients                                                               | 40   | Bulk RNA-Seq | Cell line |
| [SRP283940](SRP283940_multiqc_report.html) | Human primary brain microvascular endothelial cells transcriptome   with/without SARS-CoV-2 infection                                                                     | 6    | Bulk RNA-Seq | Cell line |
| [SRP285334](SRP285334_multiqc_report.html) | SARS-CoV-2 suppresses mRNA splicing, translation, and protein trafficking   in a multipronged mechanism to evade host defenses                                            | 19   | Bulk RNA-Seq | Cell line |
| [SRP285394](SRP285394_multiqc_report.html) | SARS-CoV-2 suppresses mRNA splicing, translation, and protein trafficking   in a multipronged mechanism to evade host defenses                                            | 73   | Bulk RNA-Seq | Cell line |
| [SRP286174](SRP286174_multiqc_report.html) | Nonstructural protein 1 of SARS-CoV-2 is a potent pathogenicity factor   redirecting host protein synthesis machinery toward viral RNA                                    | 12   | Bulk RNA-Seq | Cell line |
| [SRP286660](SRP286660_multiqc_report.html) | SARS-CoV-2 infected cells present HLA-I peptides from canonical and   out-of-frame ORFs                                                                                   | 16   | Bulk RNA-Seq | Cell line |
| [SRP286669](SRP286669_multiqc_report.html) | iPSC-derived Human Intestinal Organoids are permissive to SARS-CoV-2   infection                                                                                          | 24   | Bulk RNA-Seq | Cell line |
| [SRP286805](SRP286805_multiqc_report.html) | A genome-wide RNAi screen to identify human factors essential for   SARS-CoV-2 infection                                                                                  | 6    | Bulk RNA-Seq | Cell line |
| [SRP292198](SRP292198_multiqc_report.html) | SARS-CoV-2 on hESC-derived peripheral neurons                                                                                                                             | 4    | Bulk RNA-Seq | Cell line |
| [SRP294125](SRP294125_multiqc_report.html) | Infection of human Nasal Epithelial Cells with SARS-CoV-2 and a 382-nt   deletion isolate lacking ORF8 reveals similar viral kinetics and host   transcriptional profiles | 41   | Bulk RNA-Seq | Cell line |
| [SRP295094](SRP295094_multiqc_report.html) | SARS-CoV-2 utilizes a multipronged strategy to suppress host protein   synthesis                                                                                          | 42   | Bulk RNA-Seq | Cell line |
| [SRP295561](SRP295561_multiqc_report.html) | Immune transcriptomes of highly exposed SARS-CoV-2 asymptomatic   seropositive versus seronegative individuals from the Ischgl community                                  | 104  | Bulk RNA-Seq | Cell line |
| [SRP295687](SRP295687_multiqc_report.html) | Role of Top1 and Genome structure in SARS-CoV-2 infection [RNA-Seq human]                                                                                                 | 72   | Bulk RNA-Seq | Cell line |
| [SRP295706](SRP295706_multiqc_report.html) | A novel cell culture system modeling the SARS-CoV-2 life cycle                                                                                                            | 2    | Bulk RNA-Seq | Cell line |
| [SRP296566](SRP296566_multiqc_report.html) | SARS-CoV-2 infects human pluripotent stem cell-derived cardiomyocytes,   impairing electrical and mechanical function                                                     | 48   | Bulk RNA-Seq | Cell line |
| [SRP297170](SRP297170_multiqc_report.html) | Clofazimine is a broad-spectrum coronavirus inhibitor that antagonizes   SARS-CoV-2 replication in primary human cell culture and hamsters                                | 39   | Bulk RNA-Seq | Cell line |
| [SRP302575](SRP302575_multiqc_report.html) | Adult Stem Cell-derived Complete Lung Organoid Models Emulate Lung   Disease in COVID-19                                                                                  | 33   | Bulk RNA-Seq | Cell line |
| [SRP303317](SRP303317_multiqc_report.html) | Virus-induced senescence is a central pathogenic principle and   therapeutic target in COVID-19 disease                                                                   | 25   | Bulk RNA-Seq | Cell line |
| [SRP307098](SRP307098_multiqc_report.html) | m6A modification in SARS-CoV-2 virus regulates host cell innate immune   response                                                                                         | 16   | Bulk RNA-Seq | Cell line |
| [SRP308020](SRP308020_multiqc_report.html) | SARS-CoV-2 spike protein interacts with and activates TLR4                                                                                                                | 6    | Bulk RNA-Seq | Cell line |
| [SRP311379](SRP311379_multiqc_report.html) | hPSC-derived cells to model Macrophage-mediated inflammation in COVID19   Hearts                                                                                          | 23   | Bulk RNA-Seq | Cell line |
| [SRP311694](SRP311694_multiqc_report.html) | RNA-Seq Quantitative Analysis of the regulation of SARS-CoV-2 infection   on autophagy and apoptosis related gene transcriptome in infected cells                         | 4    | Bulk RNA-Seq | Cell line |
| [SRP312603](SRP312603_multiqc_report.html) | Comparative Transcriptomic and Molecular Pathway Analyses of HL-CZ Human   Pro-Monocytic Cells Expressing SARS-CoV-2 Spike S1, S2, NP, NSP15 and NSP16   Genes            | 21   | Bulk RNA-Seq | Cell line |
| [SRP319696](SRP319696_multiqc_report.html) | Switching of OAS1 splicing isoforms mitigates SARS-CoV-2 infection                                                                                                        | 6    | Bulk RNA-Seq | Cell line |
| [SRP324059](SRP324059_multiqc_report.html) | Viral and host transcriptomes in SARS-CoV-2 infected human lung cells                                                                                                     | 42   | Bulk RNA-Seq | Cell line |
| [SRP325484](SRP325484_multiqc_report.html) | Severe COVID-19 is Characterized by an Impaired Type I Interferon   Response and Elevated Levels of Arginase Producing Granulocytic Myeloid   Derived Suppressor Cells    | 16   | Bulk RNA-Seq | Cell line |
| [SRP325675](SRP325675_multiqc_report.html) | SARS-CoV-2 infected and uninfected VeroE6 and A549-ACE2: Bemcentinib and   liposome treatments                                                                            | 70   | Bulk RNA-Seq | Cell line |
| [SRP326251](SRP326251_multiqc_report.html) | Mapping the 3D genome and epigenome in SARS-CoV-2 infected human cells                                                                                                    | 47   | Bulk RNA-Seq | Cell line |
| [SRP327322](SRP327322_multiqc_report.html) | Transcriptome analysis of PBMCs reveals distinct immune response in the   asymptomatic and re-detectable positive COVID-19 patients                                       | 70   | Bulk RNA-Seq | Cell line |


## Other datasets

